name: ascii artwork

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest 
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
              
            - name: list file
              run: ls -ltrah
            
            - name: exc sh file
              run: sh ./ascii.sh

            # - name: print file
            #   run: cat README.md