name: ascii artwork

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest 
        steps:              
            - name: install cowsay
              run: sudo apt-get install cowsay -y
            
            - name: dragon file
              run: cowsay -f dragon "am a dragon, run away" >> dragon.txt

            - name: upload dragon file
              uses: actions/upload-artifact@v4
              with:
                name: dragon-file
                path: dragon.txt

    test_job:
        needs: first_job
        runs-on: ubuntu-latest
        steps:
          - name: download dragon file
            uses: actions/download-artifact@v4
            with:
              name: dragon-file

          - name: check for file
            run: grep -i "dragon" dragon.txt
    
    deploy_job:
      needs: [test_job]
      runs-on: ubuntu-latest
      steps:
        - name: download dragon file
          uses: actions/download-artifact@v4
          with:
            name: dragon-file

        - name: read file
          run: cat dragon.txt

        - name: deploy
          run: echo deploying........