name: first_workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest 
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
              
            - name: welcome
              run: echo "welcome"

            - name: list and read file
              run: |
                ls
                ls -ltrah
                cat README.md

            - name: ascii
              run: cowsay -f dragon "am dragon, run away" >> dragon.txt

            # - name: print file
            #   run: cat README.md

        