name: var test

on: 
  schedule:
    - cron: "* * * * *"

env:
    glb: glbval
    PASSWORD: jkhdgs!,123mlhj

jobs:
    first_job:
        env:
            jobvar: jobvarval
        
        runs-on: ubuntu-latest
        steps:
            - name: check env
              env:
                stpvar: stpvarval
              run: echo $stpvar

            - name: check env2
              env:
                stpvar2: stpvar2val
              run: echo ${{ env.stpvar2 }}

            - name: check job env
              run: echo ${{ env.jobvar }}/$jobvar

            - name: check glb var
              run: echo ${{ env.glb }}/$glb

            - name: pass
              run: echo ${{ env.PASSWORD }}

            - name: check repo creds
              run: echo ${{ vars.REPVAR }}, ${{ secrets.REPSEC }}


    second_job:
        needs: first_job
        env:
            sjb: sjbval

        runs-on: ubuntu-latest
        steps:
            - name: check env
              env:
                stvar: stvarval
              run: echo ${{ env.glb }}, ${{ env.sjb }}, ${{ env.stvar }}

